reportssite/main/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home_1, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
]

reportssite/main/models.py
from django.contrib.auth.models import User
from django.db import models


def get_name(self):
    result = None
    if self:
        if self.last_name or self.first_name:
            if self.last_name:
                if self.first_name:
                    result = self.last_name+' '+self.first_name[0]
                else:
                    result = self.last_name
            else:
                result = self.first_name
        else:
            result = self.username
        return result
    return result


def get_service_center(self):
    from servicecentres.models import ServiceCenters
    try:
        center = ServiceCenters.objects.get(user=self, is_active=True)
        return center
    except Exception:
        return None


User.add_to_class("__str__", get_name)

User.add_to_class("service_center", get_service_center)


# модель для записи действий пользователей
# взято отсюда:
# https://webdevblog.ru/logirovanie-izmeneniya-dannyh-v-modelyah-django/

ACTION_CREATE = 'create'
ACTION_UPDATE = 'update'
ACTION_DELETE = 'delete'

MODEL_CODES = 'Codes'
MODEl_PRODUCT = 'MainProducts'
MODEL_PODUCT_MODELS = 'Models'
MODE_BASE_PRICE = 'BasePrice'
MODEL_CENTER_PRICE = 'CentersPrices'
MODEL_CENTER = 'ServiceCenters'
MODEL_CONTACT = 'ServiceContacts'
MODEL_REGIONS = 'ServiceRegion'


TYPE_MODEL = (
    (MODEl_PRODUCT, 'тип продукции'),
    (MODEL_CODES, 'код дефекта'),
    (MODEL_PODUCT_MODELS, 'модель продукции'),
    (MODE_BASE_PRICE, 'базовая расценка'),
    (MODEL_CENTER_PRICE, 'индивидуальная расценка'),
    (MODEL_REGIONS, 'регион'),
    (MODEL_CENTER, 'севиснвый центр'),
    (MODEL_CONTACT, 'контакт'),
)

TYPE_ACTION_ON_MODEL = (
    (ACTION_CREATE, 'Создание'),
    (ACTION_UPDATE, 'Изменение'),
    (ACTION_DELETE, 'Удаление'),
)


class ChangeLogs(models.Model):
    changed = models.DateTimeField(
        auto_now=True,
        verbose_name=u'Дата/время изменения'
        )
    model = models.CharField(
        choices=TYPE_MODEL,
        max_length=255,
        verbose_name=u'Таблица',
        null=True
        )
    record_id = models.IntegerField(verbose_name=u'ID записи', null=True)
    user = models.ForeignKey(
        User,
        verbose_name=u'Автор изменения',
        on_delete=models.CASCADE, null=True
        )
    action_on_model = models.CharField(
        choices=TYPE_ACTION_ON_MODEL,
        max_length=50,
        verbose_name=u'Действие',
        null=True
        )
    data = models.JSONField(
        verbose_name=u'Изменяемые данные модели',
        default=dict
        )
    ipaddress = models.CharField(
        max_length=15,
        verbose_name=u'IP адресс',
        null=True
        )

    class Meta:
        ordering = ('-changed',)
        verbose_name = 'Действие пользователя'
        verbose_name_plural = 'Действия пользователей'

    def __str__(self):
        return f'{self.id}'

    @classmethod
    def add(cls, instance, user, ipaddress, action_on_model, data, id=None):
        # Создание записи в журнале регистрации изменений
        log = ChangeLogs.objects.get(id=id) if id else ChangeLogs()
        log.model = instance.__class__.__name__
        log.record_id = instance.pk
        if user:
            log.user = user
        log.ipaddress = ipaddress
        log.action_on_model = action_on_model
        log.data = data
        log.save()
        return log.pk

reportssite/main/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core import validators
from .my_validators import file_size_validation
from .models import TYPE_MODEL, TYPE_ACTION_ON_MODEL
from servicecentres.models import ServiceCenters


#форма входя на портал
class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя', widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'floatingInput'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'floatingPassword'}))


class DataFileLoadForm(forms.Form):
    file = forms.FileField(label='FileField', validators=[validators.FileExtensionValidator(['txt']), file_size_validation])


class LogsFilterForm(forms.Form):
    MODELS = list(TYPE_MODEL)
    MODELS.insert(0, ('empty', 'Все типы ...'))
    MODELS = tuple(MODELS)
    ACTIONS = list(TYPE_ACTION_ON_MODEL)
    ACTIONS.insert(0, ('empty', 'Все действия ...'))
    ACTIONS = tuple(ACTIONS)
    model = forms.ChoiceField(choices=MODELS, required=False, widget=forms.Select(attrs={'class': "form-select"}))
    action_on_model = forms.ChoiceField(choices=ACTIONS, required=False, widget=forms.Select(attrs={'class': "form-select"}))
    staff_user = forms.ModelChoiceField(queryset=User.objects.filter(is_staff=True), empty_label="Все менеджеры ...",
                                        required=False, widget=forms.Select(attrs={"class": "form-select"}))


reportssite/main/views.py
import datetime
from threading import Thread
from django.utils import timezone
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.contrib.auth import login, logout
from django.views.generic import View, ListView, TemplateView
from django.contrib import messages

from .business_logic import datafile_uploaded, datafile_get_format, STATUS_ACCEPTED, STATUS_PAYMENT, REPORT_STATUS
from reports.models import Reports, ReportsParts
from servicecentres.models import ServiceCenters, ServiceRegions
from reports.forms import ReportTitleForm
from non_repairability_act.models import NonRepairabilityAct, ActStatus, ActStatusHistory
from mail.views import mail_new_acts
from .my_validators import superuser_validation, staff_validation, StaffUserMixin, user_validation
from .forms import *
from .models import ChangeLogs


class HelpPage(TemplateView):
    template_name = 'main/help_page.html'
    

def site_stop(request):
    return render(request, 'main/site_stop.html')


def start_login(request):
    # симуляция выполнения переодических задач 
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if user.is_staff:
                return redirect('staff_home')
            else:
                try:
                    ServiceCenters.objects.get(user=request.user, is_active=True)
                    return redirect('user_home')
                except Exception:
                    messages.error(request, 'Ошибка привязки логина. Продолжение работы не возможно !')
                    return redirect('login_page')
        else:
            messages.error(request, 'Неверное имя пользовтаеля или пароль')
    else:
        form = UserLoginForm()
    return render(request, 'main/index.html', {'form': form})


#домашняя страница рядового пользователя
@user_passes_test(user_validation)
def user_home(request):
    cont = dict()
    reports = Reports.objects.filter(service_center__user=request.user)[:3]
    acts = NonRepairabilityAct.objects.filter(center__user=request.user)[:3]
    senter = get_object_or_404(ServiceCenters, user=request.user)
    ordered_parts = ReportsParts.objects.filter(record__report__in=reports, order_date__isnull=False).\
        exclude(record__report__status__in=[STATUS_ACCEPTED, STATUS_PAYMENT]).values('title', 'count')
    form = ReportTitleForm()
    paginator = Paginator(reports, 10)
    page_number = request.GET.get('page')
    cont['reports'] = reports
    cont['acts'] = acts
    cont['rep_form'] = form
    cont['senter'] = senter
    cont['parts'] = ordered_parts
    return render(request, 'main/user_home.html', cont)


#домашяя страница персоланала
@user_passes_test(staff_validation)
def staff_home_1(request):
    """ главная страницы менеджера  """

    from django.db.models import Q, Count, F

    cont = dict()
    # получение логов изменения данных
    logs = ChangeLogs.objects.all()[:3].values('pk')
    # получение данных по отчетам
    reports_data = {}
    for status in REPORT_STATUS:
        item_data = {}
        item_data['title'] = status[1] 
        item_data['count'] = Reports.objects.filter(status=status[0]).count()
        reports_data[status[0]] = item_data
    # получение данных по актам
    acts_data = {}
    acts = NonRepairabilityAct.objects.all()
    for status in ActStatus:
        item_data = {}
        item_data['title'] = status.label
        id = [act.id for act in acts if act.status.status == status]
        item_data['count'] = len(id)
        acts_data[status] = item_data
    # получение списка заказанных деталей
    parts = ReportsParts.objects.filter(order_date__isnull=False, send_number__isnull=True).\
        annotate(center_title=F('record__report__service_center__title'),\
                 center_pk=F('record__report__service_center__pk')).\
                    values('center_title', 'center_pk', 'order_date')   
    #if not request.user.is_superuser and not request.user.groups.filter(name='GeneralStaff'):
    if ServiceRegions.objects.filter(staff_user=request.user):
        parts = parts.filter(
                Q(order_date__isnull=False)&(
                Q(record__report__service_center__region__staff_user = request.user)|
                Q(record__report__service_center__staff_user = request.user)                
                )
            )
    expired_periods = [7, 14, 21]
    expired_parts = {}
    for period in expired_periods:
        count = parts.filter(
            order_date__lt=(datetime.datetime.now()-datetime.timedelta(days=period))
            ).count()
        if count:
            expired_parts[str(period)] = count
    parts = parts.annotate(count=Count('record__report__service_center__title'))
    parts_dict = {}
    for item in parts:
        if item['center_pk'] in parts_dict:
            parts_dict[item['center_pk']]['count'] += item['count']
        else:
            parts_dict[item['center_pk']] = {'count': item['count'], 'title': item['center_title'], 'pk': item['center_pk'] }

    cont['part_orders'] = parts_dict
    cont['expired_parts'] = expired_parts
    cont['staff_actions'] = logs
    cont['reports'] = reports_data
    cont['acts'] = acts_data
    return render(request, 'main/staff_home_1.html', cont)

#выход пользователя
def userlogout(request):
    logout(request)
    return redirect('login_page')


#страница загрузки моделей из файла
@user_passes_test(superuser_validation)
def admin_load_data(request, mod_name):
    cont = {'mod_name': mod_name, 'format_help': datafile_get_format(mod_name)}
    if request.method == 'POST':
        form = DataFileLoadForm(request.POST, request.FILES)
        cont['form'] = form
        if form.is_valid():
            result = datafile_uploaded(request.FILES['file'],mod_name)
            if len(result) != 0:
                msg = 'Ошибки в строках файла: ' +', '.join(result)
                messages.error(request, msg)
            redirect_url = '/admin/' + mod_name.replace('.', '/') + '/'
            return redirect(redirect_url)
    else:
        form = DataFileLoadForm()
        cont['form'] = form
    return render(request, 'main/admin_load_data.html', cont)


#базовый класс для представлений изспользующих формы - позволяет выводить сообщения валидации
class MyFormMessagesView(View):
    success_message = 'my meesage'

    def form_valid(self, form):
        messages.success(self.request, self.success_message)
        return super().form_valid(form)

    def form_invalid(self, form, **kwargs):
        ctx = self.get_context_data(**kwargs)
        text=''
        for error in form.errors:
            text = text + form.errors[error]
        messages.error(self.request, text)
        ctx['form'] = form
        return self.render_to_response(ctx)


class LogsList(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ChangeLogs
    template_name = 'main/logs_list.html'
    context_object_name = 'logs'
    extra_context = {'title': 'Изменения данных'}
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LogsFilterForm(self.request.GET)
        context['obj_count'] = self.object_list.count()
        return (context)

    def get_queryset(self):
        logs = ChangeLogs.objects.all()
        if self.request.GET.get("model", '') != '' and self.request.GET.get("model", '') != 'empty':
            logs = logs.filter(model=self.request.GET.get("model"))
        if self.request.GET.get("action_on_model", '') != '' and self.request.GET.get("action_on_model", '') != 'empty':
            logs = logs.filter(action_on_model=self.request.GET.get("action_on_model"))
        if self.request.GET.get("staff_user", '') != '':
            logs = logs.filter(user=self.request.GET.get("staff_user"))
        return logs


class MainPageView(TemplateView):
    template_name = 'main/index1.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserLoginForm(self.request.POST)
        return context

reportssite/main/templates/main/admin_load_data.html
{% extends 'admin/base_site.html' %}

{% block title %}
    Загрузка данных|Отчеты RENOVA
{% endblock %}

{% block extrastyle %}
    {{ block.super }}
    <style type="text/css">
       #centerLayer {
        margin-left: 20%; /* Отступ слева */
        width: 60%; /* Ширина слоя */
        padding: 10px; /* Поля вокруг текста */
       }
    </style>
{% endblock %}

{% comment %}{% block breadcrumbs %}
{% endblock %}{% endcomment %}

{% block content %}
    <div id="centerLayer">
        <h1>Загрузка модели из текстового файла</h1>
        <form action="" method="post" id="save_form" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Модель: {{ mod_name }}</h2>
            Требуемый формат файла: {{ format_help }} (UTF-8)
            <h2>Загружаемые данные:</h2>
            {{ form.file }}
            <p>{{ form.file.errors }}</p>
            <input type="submit" value="Записать в базу данных" class="default align-right">
        </form>
   </div>
{% endblock %}

reportssite/main/templates/main/help_page.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}


{% block title %}
    {{ block.super }}|Помощь
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_authenticated %}
    {% if request.user.is_staff %}
        {% include 'inc/staff_navbar.html' %}
    {% else %}
        {% include 'inc/user_navbar.html' %}
    {% endif %}
{% else %}
    <nav class="navbar sticky-top navbar-expand-md bg-primary" aria-label="Fourth navbar example">
        <div class="container-fluid px-5">
            <div><h1 class="text-white text-center text-sm-start">RENOVA</h1></div>
            <div class="d-flex flex-wrap justify-content-center">
                <h5><a class="nav-link text-white" href="https://renova-service.ru/">Главная</a></h5>
                <h5><a class="nav-link text-white" href="https://renova-service.ru/#hot_line">Горячая линия</a></h5>
            </div>
        </div>
    </nav>
{% endif %}

<main class="container col-10 py-4 d-flex flex-column align-items-center">
    <div class="d-flex flex-wrap justify-content-center">
        <div class="p-4">
            <h5 class="col-12 align-items-center">Основной функционал с сайта</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/b36prDfsOHw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Добавление отчета</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/-_ghBxhsI-8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Проверка записи о ремонте</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/9U2ZZbzRx90" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Возврат отчета на доработку</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/Rtck_wNbqek" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Запчасти без обязательств. Часть 1</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/D4GRjQxXt9M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Запчасти без обязательств. Часть 2</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/VkfF_VKpwJQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Перенос ремонта на следующий месяц.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/E-bvKuZeS9o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Загрузка платежных документов.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/YWLFIXK6OrI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Загрузка документов к ремонту.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/90N1kfj0j5A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Фотографии, прикаладываемые к отчету.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/5rkOL7tMG58" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>    
        </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Акты НРП. Часть 1.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/IxllF0ufTJs?si=gxRSpJ2jB2TUL_zu" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
        <div class="p-4">
            <h5 class="col-12 align-items-center">Акты НРП. Часть 2.</h5>
            <iframe width="330" height="200" src="https://www.youtube.com/embed/l6sGYrL95cE?si=OBEgb9ew-yW4xrYR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
            </div>
    </div>
    
    <!-- кнопка ВВЕРХ -->
    {% include 'inc/go_to_top_button.html' %}
</main>

{% include 'inc/footer.html' %}
{% endblock %}

reportssite/main/templates/main/logs_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% include 'inc/staff_navbar.html' %}

<div class="container">
    <main>
        <div class="row py-4 justify-content-between">
            <div class="col-auto"><h3>{{ title }}</h3></div>
            <div class="col-auto"></div>
        </div>

        <div class="row g-5">
            <div class="col-lg-5  order-lg-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Найдено записей</span>
                    <span class="badge bg-primary rounded-pill">{{ obj_count }}</span>
                </h4>
                <form class="card p-2" method="get">
                    <div class="row mb-3">
                        <label class="col-xl-4 col-form-label">Тип данных</label>
                        <div class="col-xl-8">
                            {{ form.model}}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-xl-4">Действия</label>
                        <div class="col-xl-8">
                            {{ form.action_on_model }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-xl-4">Менеджер</label>
                        <div class="col-xl-8">
                            {{ form.staff_user }}
                        </div>
                    </div>
                    <div class="container mt-2 d-flex justify-content-center gap-2">
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-search"></i>
                            выбрать
                        </button>
                        <a class="btn btn-outline-primary" href="{{ request.path }}" role="button">
                            <i class="bi bi-x-lg"></i>
                            сбросить
                        </a>
                    </div>
                </form>
            </div>

            <div class="col-lg-7  d-grid gap-3">
                {% if logs %}
                {% for action in logs %}
                {% show_log action.pk %}
                {% endfor %}
                {% else %}
                <h4 class="text-center text-muted">Ничего не найдено ...</h4>
                {% endif %}
            </div>
        </div>
        {% if logs %}
        <!-- кнопка ВВЕРХ !-->
        {% include 'inc/go_to_top_button.html' %}
        {% endif %}
    </main>
    {% include 'inc/list_paginator.html' %}
</div>

{% include 'inc/footer.html' %}
{% endblock %}

reportssite/main/templates/main/site_stop.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}


{% block title %}
    {{ block.super }}|Сайт недоступен
{% endblock %}

{% block content %}
<nav class="navbar sticky-top navbar-expand-md navbar-light bg-light" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><strong>RENOVA</strong></a>
    </div>
</nav>

<div class="container py-5 text-center">
    <h1>ИЗВИНИТЕ</h1>
    <H2>САЙТ ВРЕМЕННО НЕДОСТУПЕН !</H2>
</div>

{% include 'inc/footer.html' %}
{% endblock %}

reportssite/main/templates/main/tag_log_data.html
<div class="card mb-3">
    <div class="card-body">
        <div class="row py-1 bg-light text-dark border border-border">
            <strong>{{ action.get_model_display|capfirst }} - {{ action.get_action_on_model_display|lower }} </strong>
        </div>
        <div class="col-12 mt-1">
            {% for line in obj_description %}
            {{ line }}<br>
            {% endfor %}
        </div>
        <div class="row mt-1">
            {% for key,val in data.items %}
            <div class="row">
                <div class="col-auto"><strong>{{ key }}:</strong></div>
                <div class="col-auto">{{ val }}</div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-2">
            <div class="col-sm-4">
                <h6 class="card-title text-muted">{{ action.user }}</h6>
            </div>
            <div class="col-auto">
                <h6 class="card-title text-muted">{{ action.changed }}</h6>
            </div>
        </div>
    </div>
 </div>

reportssite/main/templates/main/tag_parts_list.html
<div class="row g-1">
    {% for part in parts %}
        {% if part.order_date %}
            <label class="col-xl-8">
                <i class="bi bi-envelope-check-fill"></i>
                <span class='pl-1'>{{ part.title|truncatewords:5 }}</span>
            </label>
        {% else %}
            <label class="col-xl-8">{{ part.title|truncatewords:5 }}</label>
        {% endif %}
    {% if part.price and part.price != 0 %}
    <label class="col-xl-4">{{ part.count }} X {{ part.price }}</label>
    {% else %}
    <label class="col-xl-4">{{ part.count }} шт</label>
    {% endif %}
    {% endfor %}
</div>

reportssite/main/templates/main/tag_products_list.html
<div class="col-lg-3">
    <div class="list-group">
        {% for product in products %}
        <a class="list-group-item list-group-item-action" href="#Item-{{ forloop.counter }}">
            {{ product.short_title }}
        </a>
        {% endfor %}
    </div>
</div>

reportssite/main/templates/main/tag_records_form_fields_errors.html
<span class="badge rounded-pill bg-danger"
      data-bs-toggle="tooltip" data-bs-html="true"
      title="{{ errors }}">
    !
</span>

reportssite/main/templates/main/tag_show_base_price_links.html
{% for item,value in base_price_type %}
<li><a class="dropdown-item" href="{% url 'prices_list_page' item %}">Расценки по прайсу "{{ value }}"</a></li>
{% endfor %}

reportssite/main/templates/main/tag_show_service_member_btn.html
<div class="position-fixed top-0 end-0" style="margin-top:68px;margin-right:20px;">
    <a data-service="{{ center_pk }}" data-bs-toggle="offcanvas" href="#offcanvasRight" role="button" aria-controls="offcanvasRight">
        <svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" class="bi bi-pencil-fill">
            <g class="layer">
            <title>Layer 1</title>
            <ellipse cx="24.9" cy="24.86" fill="#aaff56" id="svg_2" rx="23.62" ry="23.9" stroke="#000000"/>
            <path d="m32.63,12.16a0.73,0.73 0 0 0 -1.03,0l-2.42,2.41l5.45,5.45l2.41,-2.42a0.73,0.73 0 0 0 0,-1.03l-4.41,-4.41zm0.95,8.9l-5.45,-5.45l-9.55,9.55l0.31,0a0.73,0.73 0 0 1 0.73,0.73l0,0.73l0.73,0a0.73,0.73 0 0 1 0.73,0.73l0,0.73l0.73,0a0.73,0.73 0 0 1 0.73,0.73l0,0.73l0.73,0a0.73,0.73 0 0 1 0.73,0.73l0,0.31l9.55,-9.55zm-10.97,10.97a0.73,0.73 0 0 1 -0.04,-0.26l0,-0.73l-0.73,0a0.73,0.73 0 0 1 -0.73,-0.73l0,-0.73l-0.73,0a0.73,0.73 0 0 1 -0.73,-0.73l0,-0.73l-0.73,0a0.73,0.73 0 0 1 -0.73,-0.73l0,-0.73l-0.73,0a0.73,0.73 0 0 1 -0.25,-0.04l-0.26,0.26a0.73,0.73 0 0 0 -0.16,0.24l-2.94,7.35a0.73,0.73 0 0 0 0.95,0.95l7.35,-2.94a0.73,0.73 0 0 0 0.24,-0.16l0.26,-0.25z" id="svg_1" transform="matrix(1 0 0 1 0 0)"/>
            </g>
        </svg>
        {% if member_count %}
            <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                style="margin-top:5px;margin-left:-5px;">
                    {{ member_count }}
                    <span class="visually-hidden"></span>
            </span>
        {% endif %}
    </a>
</div>