reportssite/main/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home_1, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
]

reportssite/servicecentres/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('list/', ServiceCentersList.as_view(), name='centres_list_page'),
    path('add/', ServiceCentersAdd.as_view(), name='centres_add_page'),
    path('regions/', ServiceCentersRegionList.as_view(), name='centres_region_list_page'),
    path('update/<int:pk>/', ServiceCenterUpdate.as_view(), name='centres_update_page'),
    path('contacts-list/', ServiceCentersContactsList.as_view(), name='centres_contacts_page'),
    path('contact/<int:center_pk>/', ServiceCentersContactsByCenter.as_view(), name='centres_contact_page'),
    path('contact-add/', ServiceContactAdd.as_view(), name='contact_add_page'),
    path('contact-update/<int:pk>/', ServiceContactUpdate.as_view(), name='contact_update_page'),
    path('contact-delete/<int:contact_pk>/', ContactDelete, name='contact_delete_page'),
    path('export-list/', CentersListExport, name='export-list'),
    path('get-center-members/', GetServiceMembersView.as_view(), name='get-center-members'),
    path('create-center-members/', CreateServiceMemberView.as_view(), name='create-center-members'),
    path('delete-center-members/', DeleteServiceMemberView.as_view(), name='delete-center-members'),
]

reportssite/servicecentres/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.urls import reverse
from main.my_validators import ChangeloggableMixin
from main.signals import journal_save_handler, journal_delete_handler
from main.business_logic import BASE_PRICE_TYPE, PRICE_LITE


class ServiceRegions(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=50, db_index=True, verbose_name='Наименование')
    staff_user = models.ForeignKey(User, blank=True,  null=True, on_delete=models.SET_NULL, verbose_name='Менеджер', limit_choices_to={'is_staff': True})

    # def get_absolute_url(self):
    #    return reverse('news_page', kwargs={"pk": self.pk})

    class Meta():
        verbose_name = 'Регион'
        verbose_name_plural = 'Регионы'
        ordering = ['title']

    def __str__(self):
        return self.title


class ServiceCenters(ChangeloggableMixin, models.Model):
    code = models.CharField(max_length=50, db_index=True, verbose_name='Код', help_text='Код по 1С. Обязательное поле.')
    title = models.CharField(max_length=50, db_index=True, verbose_name='Наименование', help_text='Юридическое наименование. Обязательное поле.')
    city = models.CharField(max_length=50, verbose_name='Город', help_text='Город. Обязательное поле.')
    region = models.ForeignKey(ServiceRegions,  null=True,on_delete=models.PROTECT, verbose_name='Регион', help_text='Регион СЦ. Обязательное поле.')
    addr = models.CharField(max_length=350, blank=True, verbose_name='Адрес')
    post_addr = models.CharField(max_length=350, blank=True, verbose_name='Почтовый адрес')
    conditions = models.TextField(blank=True, verbose_name='Особыче условия')
    free_parts = models.BooleanField(default=False, verbose_name='Бесплатные запчасти')
    grade = models.FloatField(default=5, verbose_name='Рэйтинг', editable=False)
    note = models.TextField(blank=True, verbose_name='Примечание')
    is_active = models.BooleanField(default=True, verbose_name='Ативен')
    user = models.ForeignKey(User, related_name='user_centers', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Пользователь', limit_choices_to={'is_staff': False})
    staff_user = models.ForeignKey(User, related_name='staff_centers', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Менеджер', limit_choices_to={'is_staff': True})
    price_type = models.CharField(choices=BASE_PRICE_TYPE, max_length=100, verbose_name='Тип прайса',
                                  default=PRICE_LITE)

    def get_absolute_url(self):
        return reverse('centres_update_page', kwargs={"pk": self.pk})

    class Meta():
        verbose_name = 'Сервисный центр'
        verbose_name_plural = 'Сервисные центры'
        ordering = ['title']

    def __str__(self):
        return self.title

    def clean(self):
        if self.code and self.__class__.objects.filter(code=self.code).exclude(pk=self.pk):
            raise ValidationError("Обьект с таким кодом 1С уже существует!")


class ServiceContacts(ChangeloggableMixin, models.Model):
    name = models.CharField(max_length=150, db_index=True, verbose_name='Фамилия, имя, отчетство')
    service_center = models.ForeignKey(ServiceCenters, on_delete=models.CASCADE, verbose_name='Сервисный центр')
    funct = models.CharField(max_length=150, blank=True, verbose_name='Должность')
    tel_num = models.CharField(max_length=50, blank=True, verbose_name='Телефон')
    email = models.EmailField(blank=True, verbose_name='E-mail')
    note = models.CharField(max_length=350, blank=True, verbose_name='Примечание')

    class Meta():
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'
        ordering = ['service_center__title', 'name']

    def get_absolute_url(self):
        return reverse('contact_update_page', kwargs={"pk": self.pk})

    def __str__(self):
        return self.name


class ServiceMember(models.Model):
    text = models.CharField(
        max_length=1000, help_text='Текст замечания'
    )

    update_at = models.DateTimeField(auto_now=True)

    status = models.PositiveSmallIntegerField(default=3, help_text='Статус')

    center = models.ForeignKey(
        'ServiceCenters', on_delete=models.CASCADE, related_name='members'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Замечание к сервису'
        verbose_name_plural = 'Замечания к сервисам'
        ordering = ['status', 'update_at']

    def __str__(self):
        return (
            f'{self.center} Замечание "{str(self.text)[:30]}" '
            f'обновлено {self.update_at.strftime("%Y-%m-%d %H:%M:%S")} '
            f'пользователем {self.user}.'
        )


post_save.connect(journal_save_handler, sender=ServiceRegions)
post_delete.connect(journal_delete_handler, sender=ServiceRegions)
post_save.connect(journal_save_handler, sender=ServiceCenters)
post_delete.connect(journal_delete_handler, sender=ServiceCenters)
post_save.connect(journal_save_handler, sender=ServiceContacts)
post_delete.connect(journal_delete_handler, sender=ServiceContacts)

reportssite/servicecentres/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseForbidden, HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.edit import ProcessFormView
from django.contrib import messages
from main.my_validators import StaffUserMixin, GeneralStaffUserMixin
from main.views import MyFormMessagesView
from .forms import *
from .models import ServiceContacts, ServiceMember
from main.my_validators import staff_validation


class ServiceCentersRegionList(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ServiceRegions
    template_name = 'servicecentres/centres_regions_list.html'
    context_object_name = 'regions'
    extra_context = {'title': 'Регионы доставки запчастей'}
    paginate_by = 10
    allow_empty = True


class ServiceCentersList(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ServiceCenters
    template_name = 'servicecentres/centres_list.html'
    context_object_name = 'centres'
    extra_context = {'title': 'Сервисные центры'}
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        form = CenterFilterForm(self.request.GET)
        context['form'] = form
        context['obj_count'] = self.object_list.count()
        return (context)

    def get_queryset(self):
        centres = ServiceCenters.objects.all()
        if self.request.GET.get("staff_user", '') != '':
            centres = centres.filter(staff_user=self.request.GET.get("staff_user"))
        if self.request.GET.get("active_only", '') != '':
            centres = centres.filter(is_active=True)
        if self.request.GET.get("filter", '') != '':
            centres = centres.filter(Q(title__iregex=self.request.GET.get("filter")) | Q(city__iregex=self.request.GET.get("filter")))
        if self.request.GET.get("region", '') != '':
            centres = centres.filter(region__pk=self.request.GET.get("region"))
        return centres


class ServiceCentersAdd(LoginRequiredMixin, GeneralStaffUserMixin, MyFormMessagesView, CreateView):
    form_class = CenterCreateForm
    template_name = 'servicecentres/centres_add.html'
    extra_context = {'title': 'Добавление сервисного центра'}
    success_message = 'Сервисный центр успешно добавлен'

    def get_success_url(self):
        if 'close' in self.request.POST:
            return reverse_lazy('centres_list_page')
        else:
            return reverse_lazy('centres_update_page', args=(self.object.id,))

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['def_user'] = self.request.user
        return kwargs


class ServiceCenterUpdate(LoginRequiredMixin, StaffUserMixin, MyFormMessagesView, UpdateView):
    model = ServiceCenters
    form_class = CenterCreateForm
    template_name = 'servicecentres/centres_add.html'
    success_message = 'Обьект успешно изменен'

    def test_func(self):
        return (
            self.request.user == self.get_object().staff_user
            or self.request.user.is_superuser
            or self.request.user.groups.filter(name='GeneralStaff').exists()
            )

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['def_user'] = self.request.user
        return kwargs

    def get_success_url(self):
        if 'close' in self.request.POST:
            if 'next' in self.request.GET:
                return self.request.GET['next']+'#Item-'+str(self.object.pk)
            else:
                return reverse_lazy('centres_list_page')
        else:
            return self.request.path_info

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context['title'] = obj.title
        context['object'] = obj
        return (context)


class ServiceCentersContactsList(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ServiceContacts
    template_name = 'servicecentres/centres_contacts_list.html'
    context_object_name = 'contacts'
    extra_context = {'title': 'Контакты сервисных центров'}
    paginate_by = 21

    def get_queryset(self):
        centres = ServiceContacts.objects.all()
        if self.request.GET.get("filter", '') != '':
            centres = centres.filter(Q(service_center__title__iregex=self.request.GET.get("filter")) | Q(name__iregex=self.request.GET.get("filter")))
        return centres


class ServiceCentersContactsByCenter(LoginRequiredMixin, StaffUserMixin, ListView):
    model = ServiceContacts
    template_name = 'servicecentres/centres_contacts_list.html'
    context_object_name = 'contacts'
    extra_context = {'title': 'Контакты ораганизации '}
    allow_empty = True

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['center'] = ServiceCenters.objects.get(pk=self.kwargs['center_pk'])
        return (context)

    def get_queryset(self):
        return ServiceContacts.objects.filter(service_center_id=self.kwargs['center_pk']).select_related('service_center')


class ServiceContactAdd(LoginRequiredMixin, StaffUserMixin, MyFormMessagesView, CreateView):
    form_class = ContactCreateForm
    template_name = 'servicecentres/centres_contact_add.html'
    extra_context = {'title': 'Добавление контакта'}
    success_message = 'Контакт успешно добавлен'

    def form_valid(self, form):
        if (
            self.request.user.is_superuser
            or self.request.user.groups.filter(name='GeneralStaff').exists()
            or form.cleaned_data['service_center'].staff_user == self.request.user
        ):
            return super().form_valid(form)
        return self.form_invalid(form)

    def get_success_url(self):
        if 'close' in self.request.POST:
            return reverse_lazy('centres_contact_page', args=(self.object.service_center_id,))
        else:
            return reverse_lazy('contact_add_page')

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['staff_user'] = self.request.user
        return kwargs


class ServiceContactUpdate(LoginRequiredMixin, StaffUserMixin, MyFormMessagesView, UpdateView):
    model = ServiceContacts
    form_class = ContactCreateForm
    template_name = 'servicecentres/centres_contact_add.html'
    extra_context = {'title': 'Изменение контакта'}
    success_message = 'Контакт успешно изменен'

    def test_func(self):
        return (
            self.request.user == self.get_object().service_center.staff_user
            or self.request.user.is_superuser
            or self.request.user.groups.filter(name='GeneralStaff').exists()
            )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = self.get_object()
        context['center_id'] = obj.service_center_id
        return (context)

    def get_success_url(self):
        return reverse_lazy('centres_contact_page', args=(self.object.service_center_id,))

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['staff_user'] = self.request.user
        return kwargs


def ContactDelete(request, contact_pk):
    obj = get_object_or_404(ServiceContacts, pk=contact_pk)
    if (
        request.user.is_superuser
        or request.user == obj.service_center.staff_user
        or request.user.groups.filter(name='GeneralStaff').exists()
    ):
        reverse_id = obj.service_center_id
        obj.delete()
        messages.success(request, 'Контакт успешно удален')
        return redirect('centres_contact_page', reverse_id)
    else:
        return HttpResponseForbidden()


@user_passes_test(staff_validation)
def CentersListExport(request):
    """ выгрузка данных о сервисных центрах в соответствии с фильтром """
    
    import xlwt

    centres = ServiceCenters.objects.all()
    if request.GET.get("staff_user", '') != '':
        centres = centres.filter(staff_user=request.GET.get("staff_user"))
    if request.GET.get("active_only", '') != '':
        centres = centres.filter(is_active=True)
    if request.GET.get("filter", '') != '':
        centres = centres.filter(Q(title__iregex=request.GET.get("filter")) | Q(city__iregex=request.GET.get("filter")))
    if request.GET.get("region", '') != '':
        centres = centres.filter(region__pk=request.GET.get("region"))

    response = HttpResponse(content_type='application/ms-excel')
    disp = f'attachment; filename="SenterListData.xls"'
    response['Content-Disposition'] = disp
    workBook = xlwt.Workbook(encoding='utf-8')
    workSheet = workBook.add_sheet("Sheet_1")

    # Sheet header, first row
    boldStyle = xlwt.XFStyle()
    boldStyle.font.bold = True
    row_num = 0
    workSheet.write(row_num, 0, f'Данные о сервисных центрах', boldStyle)

    # Table header, third row
    row_num = 2
    workSheet.row(row_num).height = 600
    headerStyle = xlwt.easyxf('font: bold off, color black; borders: left thin, right thin, top thin, bottom thin;\
     pattern: pattern solid, fore_color white, fore_colour gray25; align: horiz center, vert top;')
    headerStyle.alignment.wrap = 1
    columns = ['№', 'Актив',  'Код', 'Регион', 'Наименование', 'Город', 'Адрес', 'Почтовый адрес', 'Особые условия',\

reportssite/servicecentres/templates/servicecentres/centres_add.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
{% include 'inc/staff_navbar.html' %}


<div class="container сol-sm-12">
    {{ form.get_object.title }}
    <div class="row justify-content-between py-3 mt-2">
        <div class="col-auto">
            <h2><p class="text">{{ title }}</p></h2>
        </div>
        <div class="col-auto">
            {% if object %}
            <a class="btn btn-outline-secondary" href="{% url 'centres_contact_page' object.pk %}" role="button">Контакты</a>
            <a class="btn btn-outline-secondary" href="{%url 'code_and_prices_page' object.pk %}" role="button">Расценки</a>
            {% endif %}
        </div>
    </div>

    <form class="row g-3" method="post">
        {% csrf_token %}
        <div class="col-md-2">
            <label class="form-label">Код</label>
            {{ form.code }}
        </div>
        <div class="col-md-5">
            <label class="form-label">Наименование</label>
            {{ form.title }}
        </div>
        <div class="col-md-3">
            <label class="form-label">Город</label>
            {{ form.city }}
        </div>
        <div class="col-md-2">
            <label class="form-label">Регион</label>
            {{ form.region }}
        </div>
        <div class="col-md-6">
            <label class="form-label">Юридический адрес</label>
            {{ form.addr }}
        </div>
        <div class="col-md-6">
            <label class="form-label">Фактический адрес</label>
            {{ form.post_addr }}
        </div>
        <div class="col-md-9">
            <label class="form-label">Особые условия работы</label>
            {{ form.conditions }}
        </div>
        <div class="col-md-3">
            <div class="row">
                <div class="col-12">
                    <label class="form-label">Тип прайса</label>
                    {{ form.price_type }}
                </div>
                <div class="col-12 mt-3 ">
                    <div class="row">
                        <div class="col-10">
                            <label class="form-label">Бесплатные запчасти</label>
                        </div>
                        <div class="col-2">
                           {{ form.free_parts }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <label class="form-label">Примечание</label>
            {{ form.note }}
        </div>
        <div class="col-md-2">
            <label class="form-label">Пользователь</label>
            {{ form.user }}
        </div>
        <div class="col-md-2">
            <label class="form-label">Менеджер</label>
            {{ form.staff_user }}
        </div>
        <div class="col-12">
            <div class="form-check">
                {{ form.is_active }}
                <label class="form-check-label align-items-center">активен</label>
            </div>
        </div>
        <div class="col-lg-12 text-end">
            <button type="submit" class="btn btn-outline-secondary" name="close">Записать и закрыть</button>
            <button type="submit" class="btn btn-primary" name="update">Записать и продолжить</button>
        </div>
    </form>
</div>

{% include 'inc/footer.html' %}
{% endblock %}

reportssite/servicecentres/templates/servicecentres/centres_contact_add.html
{% extends 'base.html' %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
{% include 'inc/staff_navbar.html' %}

<div class="container col-6">
    <div class="row py-4 col-6">
        <h3>{{ title }}</h3>
    </div>
    <form class="row g-3" method="post">
        {% csrf_token %}
        <div class="col-lg-6">
            <label class="form-label">Сервисный центр</label>
            {{ form.service_center }}
        </div>
        <div class="col-lg-6">
            <label class="form-label">ФИО</label>
            {{ form.name }}
        </div>
        <div class="col-lg-12">
            <label class="form-label">Должность</label>
            {{ form.tel_num }}
        </div>
        <div class="col-lg-6">
            <label class="form-label">Телефон</label>
            {{ form.tel_num }}
        </div>
        <div class="col-lg-6">
            <label class="form-label">E-mail</label>
            {{ form.email }}
        </div>
        <div class="col-lg-12">
            <label class="form-label">Дополнительно</label>
            {{ form.note }}
        </div>
        <div class="row mt-4">
            <div class="col-lg-2">
                {% if form.instance and form.instance.pk %}
                <a class="btn btn-outline-danger" href="{% url 'contact_delete_page' form.instance.pk %}" role="button">Удалить</a>
                {% endif %}
            </div>
            <div class="col-lg-10 text-end">
                {% if center_id %}
                <button type="submit" class="btn btn-primary" name="close">Записать и закрыть</button>
                {% else %}
                <button type="submit" class="btn btn-outline-secondary" name="close">Записать и закрыть</button>
                <button type="submit" class="btn btn-primary" name="save">Записать и добавить еще</button>
                {% endif %}
            </div>
        </div>
    </form>
</div>


{% include 'inc/footer.html' %}
{% endblock %}

reportssite/servicecentres/templates/servicecentres/centres_list.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% include 'inc/staff_navbar.html' %}

<div class="container">
    <main>
        <div class="row py-4 justify-content-between">
            <div class="col-auto"><h3>{{ title }}</h3></div>
            <div class="col-auto">
                {% if request.user.is_superuser or request.user|has_group:'GeneralStaff' %}
                <a class="btn btn-primary" href="{% url 'centres_add_page' %}" role="button">Добавить</a>
                {% endif %}
                <button id="exportBtn" class="btn btn-outline-secondary" style="button" data-url="{% url 'export-list' %}">Выгрузить в XLS</button>
            </div>
        </div>

        <div class="row g-5">
            <div class="col-lg-4  order-lg-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Найдено организаций</span>
                    <span class="badge bg-primary rounded-pill">{{ obj_count }}</span>
                </h4>
                <form class="card p-2" method="get">
                    <div class="row mb-3">
                        <label class="col-xl-4 col-form-label">Поиск</label>
                        <div class="col-xl-8">
                            {{ form.filter }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-xl-4 col-form-label">Регион</label>
                        <div class="col-xl-8">
                            {{ form.region }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-xl-4">Менеджер</label>
                        <div class="col-xl-8">
                            {{ form.staff_user }}
                        </div>
                    </div>
                    <div class="row mb-3">
                        <label class="col-xl-6 form-check-label">Только активные</label>
                        <div class="col-xl-6">
                            {{ form.active_only }}
                        </div>
                    </div>
                    <div class="container d-flex justify-content-center gap-2 mb-2">
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-search"></i>
                            выбрать
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'centres_list_page' %}" role="button">
                            <i class="bi bi-x-lg"></i>
                            сбросить
                        </a>
                    </div>
                </form>
            </div>
            <div class="col-lg-8 d-grid gap-3">
                {% if centres %}
                {% for item in centres %}
                <div class="card" id="Item-{{ item.pk }}">
                    <h5 class="card-header">
                        <div class="row justify-content-between">
                            <div class="col-auto">
                                {{ item.title }}
                            </div>
                            <div class="col-auto">
                                {% if item.staff_user %}
                                <small class="text-muted">{{ item.staff_user }}</small>
                                {% else %}
                                <small class="text-danger">менеджер не указан</small>
                                {% endif %}
                            </div>
                        </div>
                    </h5>
                    <div class="card-body">
                        <h5 class="card-title">{{ item.city }} ({{ item.region }})</h5>
                        <div class="row pb-2"><strong class="text-muted">{{ item.note }}</strong></div>
                        {% if item.addr %}
                        <div class="row"><label class="card-text">Юридический адрес: {{ item.addr }}</label></div>
                        {% endif %}
                        {% if item.post_addr %}
                        <div class="row"><label class="card-text">Почтовый адрес: {{ item.post_addr }}</label></div>
                        {% endif %}
                        {% if request.user.is_superuser or request.user|has_group:'GeneralStaff' or request.user == item.staff_user %}
                        <div class="row justify-content-start py-1">
                            <div class="col-auto"><i class="bi bi-coin"></i></div>
                            <div class="col"><p class="card-text">тип прайса:  {{ item.get_price_type_display}}</p></div>
                        </div>
                        {% endif %}
                        {% if item.conditions %}
                        <div class="row justify-content-start py-1">
                            <div class="col-auto"><i class="bi bi-info-square"></i></div>
                            <div class="col"><p class="card-text">{{ item.conditions }}</p></div>
                        </div>
                        {% endif %}
                        {% if item.free_parts %}
                        <div class="row justify-content-start py-1">
                            <div class="col-auto"><i class="bi bi-info-square"></i></div>
                            <div class="col"><p class="card-text">бесплатная поставка запчастей</p></div>
                        </div>
                        {% endif %}
                        <div class="row justify-content-between py-2">
                            <div class="col-auto">
                                {% if not item.is_active %}
                                <strong class="text-danger">Не активен</strong>
                                {% endif %}
                            </div>
                            <div class="col-auto">
                                <a href="{% url 'centres_contact_page' item.pk %}" class="btn btn-outline-secondary">Контакты</a>
                                {% if item.staff_user == request.user or request.user.is_superuser or request.user|has_group:'GeneralStaff' %}
                                <a href="{%url 'code_and_prices_page' item.pk %}" class="btn btn-outline-secondary">Расценки</a>
                                <a href="{%url 'reports_list' %}?service_center={{ item.pk }}" class="btn btn-outline-secondary">Отчеты</a>
                                {% if request.user|has_group:'GeneralStaff' or request.user.is_superuser or request.user == item.staff_user %}
                                    <a href="{{ item.get_absolute_url }}?next={{ request.get_full_path }}" class="btn btn-outline-success"><i class="bi bi-pencil"></i></a>
                                {% endif %}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <h4 class="text-center text-muted">Ничего не найдено ...</h4>
                {% endif %}
            </div>
        </div>

        {% if centres %}
        <!-- кнопка ВВЕРХ -->
        {% include 'inc/go_to_top_button.html' %}
        {% endif %}
    </main>
    {% include 'inc/list_paginator.html' %}
</div>

{% include 'inc/footer.html' %}

<script>
    $("#exportBtn").click(function(){
        search = window.location.search;
        url = $(this).attr("data-url");
        window.location.href = url+search;
    })
</script>


{% endblock %}