reportssite/main/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home_1, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
]

reportssite/reports/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    path(
        'report-export/<int:report_pk>',
        export_report_xls,
        name='report_export',
    ),
    path('reports-list/', ReportsForStaff.as_view(), name='reports_list'),
    path(
        'reports-user-list/',
        ReportsForUser.as_view(),
        name='reports_user_list',
    ),
    path(
        'report-change-status/',
        ReportChangeStatus,
        name='report-change-status',
    ),
    path('report-add/', ReportAdd, name='report-add'),
    path('report-update/<int:report_pk>', ReportUpdate, name='report-update'),
    path('report-send/', ReportSend, name='report-send'),
    path(
        'report-change-status/',
        ReportChangeStatus,
        name='report-change-status',
    ),
    path('report/<int:pk>', ReportDetail.as_view(), name='report_page'),
    path('report-delete/<int:report_pk>', ReportDelete, name='report_delete'),
    path('report-can-send/', ReportCanSend, name='report_can_send'),
    # ремонт, работа менеджера
    path(
        'record-for-staff/<int:pk>',
        RecordForStaff.as_view(),
        name='record-for-staff',
    ),
    path('record-add-memder/', AddRecordMember, name='record-add-member'),
    path(
        'record-delete-memder/',
        DeleteRecordMember,
        name='record-delete-member',
    ),
    path(
        'record-delete remark/',
        DeleteRecordRemark,
        name='record-delete-remark',
    ),
    path('record-verified/', RecordVerified, name='record-verified'),
    path(
        'record-cancel-verified/',
        RecordCancelVerified,
        name='record-cancel-verified',
    ),
    path(
        'record-delete-staff/', RecordDeleteStaff, name='record-delete-staff'
    ),
    path(
        'record-part-delete-staff/',
        RecordPartStaffDelete,
        name='record-part-delete-staff',
    ),
    # ремонт, работа пользователя
    path('record-add/<int:report_pk>',
        RecordAdd.as_view(),
        name='record_add_page',
    ),
    path('record-add/<int:report_pk>/<int:act_pk>',
        RecordAdd.as_view(),
        name='record_add_page',
    ),
    path('record-update/<int:pk>',
        RecordUpdate.as_view(),
        name='record_update_page',
    ),
    path('record-delete/<int:report_pk>', RecordDelete, name='record_delete'),
    path('record-copy/', RecordCopy, name='record-copy'),
    path('record-remove/', RecordRemove, name='record-remove'),
    path('ajax/codes-load/', load_codes_data, name='ajax_load_codes'),
    path('ajax/models-load/', load_models_data, name='ajax_load_models'),
    path('ajax/work-price-load/',
        load_work_price_data,
        name='ajax_load_work-price',
    ),
    path('user-ordered-parts/', OrderedParts.as_view(), name='ordered-parts'),
    path('staff-ordered-parts/',
        StaffOrderedParts.as_view(),
        name='staff-ordered-parts',
    ),
    path('send-parts/', SendParts, name='send-parts'),
    path('accept-all/', accept_all, name='accept-all'),
    path('get-record-data/', getRecordData, name='get-record-data'),
    path('get-acts', GetNonRepairabilityAct.as_view(), name='get-acts'),
]

reportssite/reports/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum, Q
from django.urls import reverse
from main.my_validators import ChangeloggableMixin
from servicecentres.models import ServiceCenters
from main.business_logic import (
    REPORT_STATUS,
    STATUS_DRAFT,
    WORKTYPE,
    FACTORIES,
    MONTH_CHOICES,
)
from products.models import Codes, MainProducts, Models
from django.db.models.signals import (
    pre_save,
    post_save,
    pre_delete,
    post_delete,
)
from django.dispatch import receiver


class ClientType(models.TextChoices):
    ORGANIZATION = 'organization', 'организация'
    INDIVIDUAL = 'individual', 'физлицо'


def ReportDateValidation(self):
    return Reports.ojects.filter(report_date=self.report_date).exclude(
        pk=self.pk
    )


class Reports(ChangeloggableMixin, models.Model):
    service_center = models.ForeignKey(
        ServiceCenters,
        on_delete=models.CASCADE,
        verbose_name='Сервисный центр',
    )
    report_date = models.DateField(verbose_name='Отчетный период')
    note = models.TextField(blank=True, null=True, verbose_name='Примечание')
    user = models.ForeignKey(
        User,
        verbose_name='Автор отчета',
        on_delete=models.PROTECT,
        limit_choices_to={'is_staff': False},
    )
    status = models.CharField(
        choices=REPORT_STATUS,
        max_length=100,
        verbose_name='Статус',
        default=STATUS_DRAFT,
    )
    total_cost = models.FloatField(
        default=0, verbose_name='Общая сумма по отчету'
    )
    total_work = models.FloatField(
        default=0, verbose_name='Общая сумма за работы'
    )
    total_part = models.FloatField(
        default=0, verbose_name='Общая сумма за детали'
    )
    total_move = models.FloatField(
        default=0, verbose_name='Общая сумма за выезд'
    )
    records_count = models.IntegerField(
        default=0, verbose_name='Количестов ремонтов'
    )
    verified_count = models.IntegerField(
        default=0, verbose_name='Количестов принятых ремонтов'
    )
    have_fault = models.BooleanField(
        default=False, blank=True, verbose_name='Имеет ошибки'
    )
    pay_date = models.DateField(
        blank=True, null=True, verbose_name='Дата передачи в оплату'
    )
    send_date = models.DateField(
        blank=True, null=True, verbose_name='Дата отправки на проверку'
    )

    class Meta:
        verbose_name = 'Отчет'
        verbose_name_plural = 'Отчеты'
        ordering = ['-report_date', 'service_center', 'status']

    def __str__(self):
        date = self.report_date
        return (f'{self.service_center.title} за'
                f'{MONTH_CHOICES[date.month-1][1]}{date.strftime(" %Y")} года')

    def get_report_month(self):
        return ' '.join(
            [
                MONTH_CHOICES[self.report_date.month - 1][1],
                self.report_date.strftime('%Y'),
            ]
        )

    def get_absolute_url(self):
        return reverse(
            'report_page',
            kwargs={
                'pk': self.pk,
            },
        )

    def get_report_documents(self):
        """формирование строки из номера акта и счета (при наличии)"""

        docs = self.reportdocumnent_set.filter(title__in=['act', 'invoice'])
        text = ''
        for doc in docs:
            text = (f'{text} {doc.get_title_display()} '
                    f'№{doc.number} от {str(doc.date)},')
        return text[:-1] if text else '...'


class ReportsRecords(ChangeloggableMixin, models.Model):
    product = models.ForeignKey(
        MainProducts, verbose_name='Тип продукции', on_delete=models.PROTECT
    )
    model = models.ForeignKey(
        Models,
        null=True,
        blank=True,
        verbose_name='Модель продукции',
        on_delete=models.PROTECT,
    )
    work_type = models.CharField(
        choices=WORKTYPE, max_length=50, verbose_name='Вид ремонта'
    )
    client_type = models.CharField(
        choices=ClientType.choices,
        max_length=50,
        null=True,
        blank=True,
        verbose_name='Тип клиента',
    )
    client = models.CharField(
        max_length=150, null=True, blank=True, verbose_name='Клиент'
    )
    client_phone = models.CharField(
        max_length=150, null=True, blank=True, verbose_name='Телефон клиента'
    )
    client_addr = models.CharField(
        max_length=250, null=True, blank=True, verbose_name='Адрес клиента'
    )
    client_email = models.EmailField(
        max_length=500, null=True, blank=True, verbose_name='E-mail клиента'
    )
    model_description = models.CharField(
        max_length=150, verbose_name='Модель продукции', blank=True
    )
    serial_number = models.CharField(
        max_length=30, verbose_name='Серийный номер'
    )
    buy_date = models.DateField(
        null=True, blank=True, verbose_name='Дата покупки'
    )
    start_date = models.DateField(verbose_name='Дата начала ремонта')
    end_date = models.DateField(
        null=True, blank=True, verbose_name='Дата окончания ремонта'
    )
    work_cost = models.FloatField(default=0, verbose_name='За работу')
    move_cost = models.FloatField(
        default=0, verbose_name='За выезд', blank=True
    )
    problem_description = models.TextField(verbose_name='Описание проблемы')
    work_description = models.TextField(
        verbose_name='Описание работ', blank=True
    )
    code = models.ForeignKey(
        Codes,
        verbose_name='Код неисправности',
        on_delete=models.PROTECT,
        limit_choices_to={'is_folder': False},
    )
    note = models.CharField(
        max_length=250, verbose_name='Примечание', blank=True
    )
    report = models.ForeignKey(
        Reports,
        verbose_name='Отчет',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    parts_cost = models.FloatField(
        default=0, verbose_name='За детали', blank=True
    )
    total_cost = models.FloatField(
        default=0, verbose_name='Всего за ремонт', blank=True
    )

    verified = models.BooleanField(default=False, verbose_name='Принят')
    factory = models.CharField(
        choices=FACTORIES,
        null=True,
        max_length=1,
        verbose_name='Завод-изготовитель',
        blank=True,
    )
    main_date = models.DateField(
        null=True, verbose_name='Дата производства', blank=True
    )
    shift = models.CharField(
        null=True, max_length=1, verbose_name='Рабочая смена', blank=True
    )
    errors = models.TextField(verbose_name='Ошибки', null=True, blank=True)
    remarks = models.TextField(verbose_name='Замечания', null=True, blank=True)
    have_general_errors = models.BooleanField(
        default=False, verbose_name='Требует внимания старшего менеджера'
    )
    verified_date = models.DateField(
        verbose_name='Дата приема записи', null=True, blank=True
    )
    order_parts = models.BooleanField(
        default=False, verbose_name='Запчасти заказаны'
    )
    # 20.01.2024. Заполнение на основании Акта НРП.
    parent_act = models.ForeignKey(
        'non_repairability_act.NonRepairabilityAct',
        null=True,
        blank=True,
        related_name='child_record',
        verbose_name='Акт-основание',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Ремонт'
        verbose_name_plural = 'Ремонты'
        ordering = [
            'report',
        ]

    def get_absolute_url(self):
        return reverse(
            'record_update_page',
            kwargs={
                'pk': self.pk,
            },
        )

    def __str__(self):
        return str(self.report) + ' ' + self.serial_number

    @property
    def status(self):
        if self.end_date:
            status = 'work_end'
        else:
            status = 'draft'
            parts = self.reportsparts_set.all()
            parts_order_count = parts.filter(order_date__isnull=False).count()
            parts_send_count = parts.filter(
                order_date__isnull=False, send_date__isnull=False
            ).count()
            if parts_order_count:
                status = 'order_part'
                if parts_send_count:
                    if parts_send_count == parts_send_count:
                        status = 'part_send_all'
                    else:
                        status = 'part_send_few'
        return status


class ReportsParts(ChangeloggableMixin, models.Model):
    title = models.CharField(max_length=250, verbose_name='Наименование')
    price = models.IntegerField(null=True, blank=True, verbose_name='Цена')
    count = models.IntegerField(null=True, verbose_name='Количество')
    document = models.CharField(
        null=True,
        blank=True,
        max_length=250,
        verbose_name='Реквизиты накладной',
    )
    record = models.ForeignKey(
        ReportsRecords, verbose_name='Отчет', on_delete=models.CASCADE
    )
    order_date = models.DateField(
        null=True, verbose_name='Дата заказа', blank=True
    )
    send_date = models.DateField(
        null=True, verbose_name='Дата отправки', blank=True
    )
    send_number = models.CharField(
        null=True, max_length=250, verbose_name='Номер РПО', blank=True
    )

    class Meta:
        verbose_name = 'Деталь из ремонта'
        verbose_name_plural = 'Детали из ремонта'
        ordering = ['record', 'title']

    def __str__(self):
        return self.title


class RecordMembers(models.Model):

    record = models.ForeignKey(
        ReportsRecords, on_delete=models.CASCADE, verbose_name='Запись'
    )
    text = models.TextField(verbose_name='Текст заметки')

reportssite/upload/models.py
""" модели загружаемых файлов  """
from os.path import splitext
from uuid import uuid4
from django.db import models
from django.core.validators import FileExtensionValidator
from reports.models import Reports, ReportsRecords


# виды документов? прилагаемых к отчету
REPORT_ACT = 'act'
REPORT_INVOICE = 'invoice'
REPORT_NETTING = 'netting'
OTHER = 'other'

REPORT_DOCUMENT = (
    (REPORT_ACT, 'Акт'),
    (REPORT_INVOICE, 'Счет'),
    (REPORT_NETTING, 'Акт взаимозачета'),
    (OTHER, 'Другое')
)


def document_name(instance, filename):
    """ функция генерации пути сохранения медиафайла """
    return f'report_document/{str(instance.report.pk)}/{uuid4().hex}{splitext(filename)[1]}'


class ReportDocumnent(models.Model):
    """ документ отчета """

    report = models.ForeignKey(
        Reports, verbose_name='Отчет', on_delete=models.CASCADE, null=False, blank=False)
    title = models.CharField(
        choices=REPORT_DOCUMENT, verbose_name='Наименование документа', max_length=20, null=False, blank=False)
    number = models.CharField(
        verbose_name='Номер документа', max_length=20, null=False, blank=False)
    date = models.DateField(
        verbose_name='Дата документа', null=False, blank=False)
    file = models.FileField(
        verbose_name='Файйл документа', upload_to=document_name, null=False, blank=False,
        validators=[FileExtensionValidator( ['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls', 'jpeg'] )]
        )

    class Meta():
        verbose_name = 'Документ отчета'
        verbose_name_plural = 'Документы отчетов'
        ordering = ['report', 'title']


    def __str__(self):
        return f'{self.report} {self.get_title_display()} №{self.number} от {self.date}'
    

    def delete(self, *args, **kwargs):
        """ удаление файла вместе с удалением объекта """
        # До удаления записи получаем необходимую информацию
        storage = self.file.storage
        path = self.file.path
        # Удаляем сначала модель ( объект )
        super(ReportDocumnent, self).delete(*args, **kwargs)
        # Потом удаляем сам файл
        storage.delete(path)


def record_document_name(instance, filename):
    """ функция генерации пути сохранения медиафайла документа ремонта """
    return f'record_document/{str(instance.record.pk)}/{uuid4().hex}{splitext(filename)[1]}'


class RecordDocumnent(models.Model):
    """ документ ремонта """

    record = models.ForeignKey(
        ReportsRecords, verbose_name='Ремонт', on_delete=models.CASCADE, null=False, blank=False)
    title = models.CharField(
        max_length=255, verbose_name='Наименование документа', null=False, blank=False)
    number = models.CharField(
        verbose_name='Номер документа', max_length=20, null=False, blank=False)
    date = models.DateField(
        verbose_name='Дата документа', null=False, blank=False)
    file = models.FileField(
        verbose_name='Файйл документа', upload_to=record_document_name, null=False, blank=False,
        validators=[FileExtensionValidator( ['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls', 'jpeg'] )]
        )

    class Meta():
        verbose_name = 'Документ ремонта'
        verbose_name_plural = 'Документы ремонта'
        ordering = ['record', 'title']


    def __str__(self):
        return f'{self.record.report} {self.record} {self.title} №{self.number} от {self.date}'
    

    def delete(self, *args, **kwargs):
        """ удаление файла вместе с удалением объекта """
        # До удаления записи получаем необходимую информацию
        storage = self.file.storage
        path = self.file.path
        # Удаляем сначала модель ( объект )
        super(RecordDocumnent, self).delete(*args, **kwargs)
        # Потом удаляем сам файл
        storage.delete(path)

reportssite/reports/templates/reports/codes_list_get.html
<option>---------</option>
{% for group in groups %}
<optgroup label="{{ group }}">
    {% for code in codes %}
    {% if code.parent.pk == group.pk %}
        {% if code.pk == select_id %}
        <option selected value="{{ code.pk }}">{{ code }}</option>
        {% else %}
        <option value="{{ code.pk }}">{{ code }}</option>
        {% endif %}
    {% endif %}
    {% endfor %}
{% endfor %}

reportssite/reports/templates/reports/get_acts.html
{% if acts %}
    <h5>Подтвержденные акты НРП:</h5>
    {% for act in acts %}
        <div class="card text-dark bg-light border border-dark ro shadow mb-3">
            <div class="card-header row justify-content-between">
                <div class="col-auto">Акт №{{ act.pk }} от {{ act.doc_date }}</div>
                <div class="col-auto">
                    <a href="{% url 'record_add_page' reportPk act.pk %}" class="btn btn-outline-primary btn-sm">
                        выбрать
                    </a>
                </div>
            </div>
            <div class="card-body">
                <h6 class="card-title my-0">
                    {{ act.product__title }} {{ act.model_description }} {{ act.serial_number }}
                </h6>
                {% if act.client %}
                    <p class="card-text my-0">Клшиент: {{ act.client }}</p>
                {% endif %}
                {% if act.shop %}
                    <p class="card-text my-0">Продавец: {{ act.shop }}</p>
                {% endif %}
            </div>
        </div>
    {% endfor %}
{% else %}
    <h5 class="text-center">У вас нет подтвержденных актов НРП !</h5>
{% endif %}

reportssite/reports/templates/reports/get_record_data.html
<div>
    <div class="mb-2">
        <h4 class="modal-title" id="recordDataLabel_{{ report.pk }}">{{ record.report.service_center }}</h4>
        <div style="font-size:0.9rem">{{ record.report.service_center.post_addr }}</div>
        {% for contact in record.report.service_center.servicecontacts_set.all %}
            <div style="font-size:0.9rem">
                {{ contact.name }}, {{ contact.tel_num }}, {{ contact.email }}
            </div>
        {% endfor %}
    </div>
    <p><strong>
        {{ record.product.title }}<br>
        {{ record.model_description }}
        SN:{{ record.serial_number }}
    </strong></p>
    <p>
        <strong>Клиент:  </strong>
        {% if record.client %}
            {{ record.client }} ({{ record.client_phone }})
        {% else %}
            предторговый ремонт
        {% endif %}
    </p>
    <p><strong>Неисправность:  </strong>{{ record.problem_description }}</p>
    <p><strong>Код:  </strong>{{ record.code }}</p>
    <p>
        {% if record.buy_date %}
            <strong>Дата продажи:  </strong>{{ record.buy_date }}<br>
        {% endif %}
        <strong>Дата начала ремонта:  </strong>{{ record.start_date }}
    </p>
    <p class="mb-0"><strong>Все детали: </strong></p>
    <ul class="my-0 py-0">
        {% for part in record.reportsparts_set.all %}
            <li class="my-0 py-0">
                {{ part }} - {{ part.count }} шт
                {% if not part.order_date %}
                    X {{ part.price }} руб
                {% endif %} 
            </li>                                                               
        {% endfor %}
    </ul>
    {% if record.recorddocumnent_set.all %}
        <p class="mt-3 mb-0"><strong>Приложенные файлы: </strong></p>
        <ul class="my-0 py-0">
            {% for doc in record.recorddocumnent_set.all %}
                <li>
                <a href='{{ doc.file.url }}' class='text-decoration-none' target="_blank">{{ doc.title }} №{{ doc.number }} от {{ doc.date|date:'d.m.y' }}</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p class="text-muted my-3">Файлы не приложены ...</p>
    {% endif %}
</div>

reportssite/reports/templates/reports/models_list_get.html
<option>---------</option>
{% for group in groups %}
<option value="{{ group.pk }}">{{ group }}</option>
{% endfor %}

reportssite/reports/templates/reports/ordered_parts.html
{% extends 'base.html' %}
{% load static %}
{% load my_tags %}

{% block title %}
    {{ block.super }}|Заказы ЗЧ
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
{% include 'inc/staff_navbar.html' %}
{% else %}
{% include 'inc/user_navbar.html' %}
{% endif %}

<div class="container">

    <h3 class="py-4">Ваши текущие заказы</h3>

    <div class="row g-5">
            <div class="col-lg-4  order-lg-last">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Найдено деталей</span>
                    <span class="badge bg-primary rounded-pill">{{ obj_count }}</span>
                </h4>
                <form class="card p-2" method="get">
                    <div class="row mb-3">
                        <label class="col-xl-3 col-form-label">Поиск</label>
                        <div class="col-xl-9">
                            {{ form.filter }}
                        </div>
                    </div>
                    <div class="container d-flex justify-content-center gap-2">
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-search"></i>
                            выбрать
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'ordered-parts' %}" role="button">
                            <i class="bi bi-x-lg"></i>
                            сбросить
                        </a>
                    </div>
                </form>
                <div class="card mt-2">
                    <h5 class="card-header">Специалист по работе с заказами:</h5>
                    <div class="card-body">
                        <strong>{{ center.region.staff_user.last_name }} {{ center.region.staff_user.first_name }}</strong>                      
                        <div><a href="mailto:{{ region.staff_user.email }}">{{ center.region.staff_user.email }}</a></div>
                    </div>
                </div>
            </div>

            <div class="col-lg-8 d-grid gap-3">
                {% if reports %}
                    {% for report in reports %}
                    <div>
                        <div class="row border p-3">
                            <div class="bg-light border border-dark rounded-3 mb-1">
                                <h5>Отчет за {{ report.report_date|date:"F Y"|lower }} ({{ report.get_status_display }})</h5>
                            </div>
                            {% for record in records %}
                                {% if record.report == report.pk %}  
                                <div>
                                    <h6>
                                        {{ record.product__title }}
                                        {{ record.model_description }}
                                        SN:{{ record.serial_number }}
                                    </h6>    
                                    <ul>
                                    {% for part  in parts %}
                                        {% if part.record == record.pk %}
                                            <li>
                                                <div class="row justify-content-between">
                                                    <div class="col-auto">
                                                        {{ part.title }}-{{ part.count }}шт
                                                    </div>
                                                    <div class="col-auto">
                                                        {% if part.send_number %}
                                                            {{ part.send_date|date:"j M Y" }}, {{ part.send_number }}
                                                        {% else %}
                                                            <span class="text-danger">обработка</span>
                                                        {% endif %}
                                                    </div>
                                                <div>
                                            </li>
                                        {% endif %}                   
                                    {% endfor %}
                                    </ul>
                                </div>
                                {% endif %}
                            {% endfor %}  
                        </div>  
                    </div>          
                    {% endfor %}
                {% else %}
                <h4 class="text-center text-muted">Ничего не найдено ...</h4>
                {% endif %}
            </div>
        </div>

         <!-- кнопка ВВЕРХ -->
        {% if reports %}  
            {% include 'inc/go_to_top_button.html' %}
        {% endif %}

        {% include 'inc/list_paginator.html' %}    

    </div>

{% include 'inc/footer.html' %}
{% endblock %}

reportssite/reports/templates/reports/price_get.html
{{ price }}