reportssite/main/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', start_login, name='login_page'),
    #path('', site_stop),
    path('user_home/', user_home, name='user_home'),
    path('logout/', userlogout, name='user_logout'),
    path('staff_home/', staff_home_1, name='staff_home'),
    path('load_data/<str:mod_name>/', admin_load_data, name='admin_load_data_page'),
    path('help/', HelpPage.as_view(), name='help_page'),
    path('logs_list/', LogsList.as_view(), name='logs_page'),
]

reportssite/non_repairability_act/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list/', views.ActListView.as_view(), name='act-list'),
    path('user/create/', views.ActCreateView.as_view(), name='act-create'),
    path(
        'user/update/<int:pk>/',
        views.ActUpdateView.as_view(),
        name='act-user-update',
        ),
    path(
        'user/delete/<int:pk>/',
        views.ActDeleteView.as_view(),
        name='act-user-delete',
        ),
    path(
        'user/get-models/', views.GetModelView.as_view(), name='act-get-models'
    ),
    path('user/get-codes/', views.GetCodeView.as_view(), name='act-get-codes'),
    path('user/del-file/', views.DelFileView.as_view(), name='act-del-file'),
    path(
        'staff/detail/<int:pk>/',
        views.ActDeatailForStaffView.as_view(),
        name='act-staff-detail',
    ),
    path(
        'staff/delete/<int:pk>/',
        views.ActDeleteView.as_view(),
        name='act-staff-delete',
    ),
    path(
        'staff/status/change/',
        views.ActStaffChangeStatusView.as_view(),
        name='act-staff-change-status',
    ),
    path(
        'staff/member/add/',
        views.ActAddMemberView.as_view(),
        name='act-staff-add-member',
    ),
    path(
        'staff/member/delete/',
        views.ActDeleteMemberView.as_view(),
        name='act-delete-member',
    ),
    path(
        'staff/user-member/delete/',
        views.ActDeleteUserMemberView.as_view(),
        name='act-delete-user-member',
    ),
    path('print/<int:pk>', views.download_pdf, name='act-download'),
    path(
        'check/<int:pk>/', views.ActDetailCheckView.as_view(), name='act-check'
    ),
]

reportssite/non_repairability_act/models.py
import datetime
from os.path import splitext
from uuid import uuid4
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User

from main.business_logic import WORKTYPE
from reports.models import ReportsRecords
from main.business_logic import parse_serial
from reports.models import ClientType


class DeviceLocation(models.TextChoices):
    CLIENT = (
        'client',
        'выдать клиенту для предъявления в торгующую организацию',
    )
    WORKSHOP = 'workshop', 'оставить в сервисном центре для разбора'
    MANUFACTURE = 'manufacture', 'вернуть производителю'


class ActStatus(models.TextChoices):
    DRAFT = 'draft', 'черновик'
    SEND = 'send', 'отправлен на проверку'
    REFINEMENT = 'refinement', 'на доработке'
    SEND_AGAIN = 'send_again', 'отправлен повторно'
    RECEIVED = 'received', 'на проверке'
    ACCEPTED = 'accepted', 'принят на рассмотрение'
    CONFIRMED = 'confirmed', 'подтвержден'
    COMPENSATED = 'compensated', 'компенсирован'


class DocumentType(models.TextChoices):
    CHECK = 'check', 'Чек/накладная'
    PHOTO = 'photo', 'Фото'
    CLAIM = 'claim', 'Претензия'
    OTHER = 'other', 'Другое'


class ActStatusHistory(models.Model):
    act = models.ForeignKey(
        'NonRepairabilityAct',
        on_delete=models.CASCADE,
        related_name='statuses',
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        choices=ActStatus.choices, max_length=20, default=ActStatus.DRAFT
    )

    class Meta:
        verbose_name = 'Статус акта'
        verbose_name_plural = 'Статусы актов'
        ordering = ['-created_at']

    def __str__(self):
        return (
            f'{self.act} Cтатус "{self.get_status_display()}" '
            f'установлен {self.created_at.strftime("%Y-%m-%d %H:%M:%S")} '
            f'пользователем {self.user}.'
        )


class ActMember(models.Model):
    text = models.CharField(
        max_length=1000, default=ActStatus.DRAFT, help_text='Текст замечания'
    )

    created_at = models.DateTimeField(auto_now_add=True)

    for_center = models.BooleanField(
        default=False, blank=True, help_text='Замечание для СЦ'
    )

    act = models.ForeignKey(
        'NonRepairabilityAct', on_delete=models.CASCADE, related_name='members'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Замечание к акту'
        verbose_name_plural = 'Замечания к актам'
        ordering = ['-created_at']

    def __str__(self):
        return (
            f'{self.act} Замечание "{str(self.text)[:30]}" '
            f'добавлено {self.created_at.strftime("%Y-%m-%d %H:%M:%S")} '
            f'пользователем {self.user}.'
        )


def document_name(instance, filename):
    """функция генерации пути сохранения медиафайла"""

    return f'act_document/{str(instance.act.pk)}/{uuid4().hex}\
        {splitext(filename)[1]}'


class ActDocumnent(models.Model):
    """документ акт"""

    title = models.CharField(
        choices=DocumentType.choices,
        max_length=20,
        help_text='Наименование документа',
    )
    number = models.CharField(max_length=20, help_text='Номер документа')
    file = models.FileField(
        upload_to=document_name,
        validators=[
            FileExtensionValidator(
                ['pdf', 'doc', 'docx', 'jpg', 'png', 'xlsx', 'xls', 'jpeg']
            )
        ],
    )

    date = models.DateField(help_text='Дата документа')

    act = models.ForeignKey(
        'NonRepairabilityAct',
        on_delete=models.CASCADE,
        related_name='documents',
    )

    class Meta:
        verbose_name = 'Документ акта'
        verbose_name_plural = 'Документы актов'
        ordering = ['act', 'title']

    def __str__(self):
        return f'{self.act} {self.get_title_display()}\
              №{self.number} от {self.date}.'

    def delete(self, *args, **kwargs):
        """удаление файла вместе с удалением объекта"""
        # До удаления записи получаем необходимую информацию
        storage = self.file.storage
        path = self.file.path
        # Удаляем сначала модель ( объект ) и потом удаляем сам файл
        super(ActDocumnent, self).delete(*args, **kwargs)
        storage.delete(path)


class NonRepairabilityAct(models.Model):
    model_description = models.CharField(
        max_length=150, null=True, blank=True, help_text='Модель продукции'
    )
    serial_number = models.CharField(
        max_length=30, null=True, blank=True, help_text='Серийный  номер'
    )
    work_type = models.CharField(
        choices=WORKTYPE,
        max_length=50,
        null=True,
        blank=True,
        help_text='Тип ремонта',
    )
    completeness = models.CharField(
        max_length=1000, blank=True, null=True, help_text='Комплектация'
    )
    problem_description = models.CharField(
        max_length=1000, blank=True, null=True, help_text='Заявленный дефект'
    )
    client_type = models.CharField(
        choices=ClientType.choices,
        max_length=50,
        blank=True,
        null=True,
        help_text='Тип клиента',
    )
    client = models.CharField(
        max_length=150, blank=True, null=True, help_text='ФИО клиента'
    )
    client_phone = models.CharField(
        max_length=150, blank=True, null=True, help_text='Телефон клиента'
    )
    client_addr = models.CharField(
        max_length=350, blank=True, null=True, help_text='Адрес клиента'
    )
    client_email = models.EmailField(
        max_length=500, blank=True, null=True, help_text='E-mail клиента'
    )
    shop = models.CharField(
        max_length=150,
        blank=True,
        null=True,
        help_text='Наименование продавца',
    )
    shop_phone = models.CharField(
        max_length=150, blank=True, null=True, help_text='Телефон продавца'
    )
    shop_addr = models.CharField(
        max_length=350, blank=True, null=True, help_text='Адрес продавца'
    )
    work_description = models.CharField(
        max_length=1000,
        blank=True,
        null=True,
        help_text='Выявленная неиспраность',
    )
    decree = models.CharField(
        max_length=250, blank=True, null=True, help_text='Заключение'
    )
    device_location = models.CharField(
        choices=DeviceLocation.choices,
        max_length=350,
        blank=True,
        null=True,
        help_text='Местонахождение изделия',
    )
    note = models.CharField(
        max_length=2000, blank=True, null=True, help_text='Примечание'
    )
    member_for_user = models.CharField(
        max_length=1000, blank=True, null=True, help_text='Заметка для сервиса'
    )

    doc_date = models.DateField(null=True, help_text='Дата документа')
    buy_date = models.DateField(
        null=True, blank=True, help_text='Дата покупки'
    )
    receipt_date = models.DateField(
        null=True, blank=True, help_text='Дата приемки'
    )

    center = models.ForeignKey(
        'servicecentres.ServiceCenters',
        on_delete=models.CASCADE,
        related_name='non_repairability_acts',
    )
    product = models.ForeignKey(
        'products.MainProducts',
        on_delete=models.SET_NULL,
        related_name='non_repairability_acts',
        null=True,
        blank=True,
        help_text='Вид продукции',
    )
    model = models.ForeignKey(
        'products.Models',
        on_delete=models.SET_NULL,
        related_name='non_repairability_acts',
        default=None,
        null=True,
        blank=True,
        help_text='Модель продукции',
    )
    code = models.ForeignKey(
        'products.Codes',
        on_delete=models.SET_NULL,
        related_name='non_repairability_acts',
        default=None,
        null=True,
        blank=True,
        help_text='Код дефекта',
    )

    class Meta:
        verbose_name = 'Акт неремонтопригодности'
        verbose_name_plural = 'Акты неремонтопригодности'
        ordering = ['-doc_date']

    def __str__(self):
        return f'Акт НРП №{self.pk} от {self.doc_date}.\
              {self.center}({self.center.city}).'

    def get_absolute_url(self):
        return reverse_lazy('act-user-update', kwargs={'pk': self.pk})

    @property
    def status(self):
        return self.statuses.filter(act=self).first()

    @property
    def repairs(self):
        return ReportsRecords.objects.filter(
            product=self.product, serial_number__iexact=self.serial_number
        ).values(
            'report__service_center__pk',
            'report__service_center__title',
            'report__service_center__city',
            'report__status',
            'pk',
            'end_date',
            'code__code',
            'code__title',
        )

    def add_status(self, new_status, user):
        if not self.status or (self.status.status != new_status):
            ActStatusHistory.objects.create(
                act=self,
                user=user,
                created_at=timezone.now(),
                status=new_status,
            )

    def add_member(self, text, for_center, user):
        ActMember.objects.create(
            act=self,
            user=user,
            created_at=timezone.now(),
            text=text,
            for_center=for_center,
        )

    def delete_member(self, member_pk):
        self.members.get(pk=member_pk).delete()

    @property
    def send_errors(self):
        REQUIRED_FIELDS = 'Обязательное поле !'

        result = {}

        def add_error(field, text):

reportssite/non_repairability_act/templates/non_repairability_act/check.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}

{% block title %}
    {{ block.super }}|{{ title }}
{% endblock %}

{% block content %}

<div class="container">
    <main class="row mt-4 justify-content-between p-2">

        <div class="col-lg-9 px-lg-4">
            <!-- Заголовок -->
            <div class="row border border-dark rounded shadow px-3 py-2 mb-2 bg-body rounded">
                <div class="col-sm-10">
                    <h3 class="mb-0 text-primary">
                        Акт № {{ act.pk }} от {{ act.doc_date}}
                    </h3>
                    <h4>
                        {{ act.center.title }} ({{ act.center.city }})
                    </h4>
                </div>
                <div class="col-sm-2 text-center">
                    {{ act.status|colored_act_status|safe }}
                </div>
            </div>
            <!-- Основная часть данных -->
            <div class="row border border-dark rounded shadow p-3 pb-4 my-2 bg-body rounded gy-1">
                <div class="col-12 col-sm-3 text-muted">Вид продукции</div>
                <div class="col-12 col-sm-9">{{ act.product }}</div>
                <div class="col-12 col-sm-3 text-muted">Модель</div>
                <div class="col-12 col-sm-9">{{ act.model_description }}</div>
                <div class="col-12 col-sm-3 text-muted">Серийный номер</div>
                <div class="col-12 col-sm-9">{{ act.serial_number }}</div>
                <div class="col-12 col-sm-3 text-muted">Дата продажи клиенту</div>
                <div class="col-12 col-sm-9">
                    {% if act.work_type == 'pretrading' %}
                        предторговый
                    {% else %}
                        {{ act.buy_date }}
                    {% endif %}
                </div>
                <div class="col-12 col-sm-3 text-muted">Дата поступления в СЦ</div>
                <div class="col-12 col-sm-9">{{ act.receipt_date }}</div>
                {% if act.repairs %}
                    <div class="col-12 col-sm-3 text-muted">Ремонты</div>
                    <div class="row col-12 col-sm-9">
                    {% for repair in act.repairs %}
                        <div class="col-12">
                            <div>{{ repair.report__service_center__title }} ({{ repair.report__service_center__city }}), {{ repair.end_date }}</div>
                            <div>{{ repair.code__code }} {{ repair.code__title }}</div>
                        </div>
                    {% endfor %}
                    </div>
                {% endif %}
                {% if act.completeness %}
                    <div class="col-12 col-sm-3 text-muted">Комплектность</div>
                    <div class="col-12 col-sm-9">{{ act.completeness }}</div>
                {% endif %}
                <div class="col-12 col-sm-3 text-muted">Заявленная неисправность</div>
                <div class="col-12 col-sm-9">{{ act.problem_description }}</div>
                {% if act.client %}
                    <div class="col-12 col-sm-3 text-muted">Клиент</div>
                    {% if act.client_type == 'organization' %}
                        <div class="col-12 col-sm-9 text-primary">организация</div>
                        <div class="col-12 col-sm-3 text-muted"></div>
                    {% endif %}
                    <div class="col-12 col-sm-9">
                        {{ act.client }}
                        {% if act.client_phone %}
                            , {{ act.client_phone }}
                        {% endif %}
                        {% if act.client_addr %}
                            , {{ act.client_addr }}
                        {% endif %}
                        {% if act.client_email %}
                            , {{ act.client_email }}
                        {% endif %}
                    </div>
                {% endif %}
                <div class="col-12 col-sm-3 text-muted">Продавец</div>
                <div class="col-12 col-sm-9">
                    {{ act.shop }} , {{ act.shop_phone }} , {{ act.shop_addr }}
                </div>
                <div class="col-12 col-sm-3 text-muted">Выявленная неисправность</div>
                <div class="col-12 col-sm-9">{{ act.work_description }}</div>
                {% if act.code %}
                    <div class="col-12 col-sm-3 text-muted">Код неисправности</div>
                    <div class="col-12 col-sm-9">{{ act.code }}</div>
                {% endif %}
                <div class="col-12 col-sm-3 text-muted">Заключение</div>
                <div class="col-12 col-sm-9"><strong>{{ act.decree }}</strong></div>
                <div class="col-12 col-sm-3 text-muted">Местонахождение изделия</div>
                {% if act.device_location %}
                <div class="col-12 col-sm-9">{{ act.get_device_location_display }}</div>
                {% else %}
                <div class="col-12 col-sm-9"><strong class="text-danger">местнахождение не определено !</strong></div>
                {% endif %}
            </div>
            <!-- Файлы и Итог -->
            <div class="row justify-content-center">
                <!-- Файлы -->
                {% if act.documents.all %}
                    <div class="col-md-8 ">
                        <div class="row me-md-1 border border-dark rounded shadow p-3 mb-2 mb-md-0 bg-body rounded">
                            <h5>Приложенные файлы:</h5>
                            {% for doc in act.documents.all %}
                                <div class="col-12"><a href='{{ doc.file.url }}' class='text-decoration-none' target="_blank">{{ doc.get_title_display }} №{{ doc.number }} от {{ doc.date|date:'d.m.y' }}</a></div>                        
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        <!-- История -->
        <div class="col col-lg-3 my-3 my-lg-0">
            <div class="row border border-dark rounded shadow p-3 bg-body rounded">
                <h5 class="p-0">История:</h5>
                {% for status in act.statuses.all %}
                    <div class="mt-2 border border-dark rounded bg-light pb-2" style="font-size:0.9em">
                        <strong>{{ status.get_status_display }}</strong>
                        <div>{{ status.created_at }}</div>
                        <div>{{ status.user }}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
    
</div>


{% include 'inc/footer.html' %}


{% endblock %}

reportssite/non_repairability_act/templates/non_repairability_act/get_codes.html
<option value="">---------</option>
{% for group in groups %}
    <optgroup label="{{ group }}">
    {% for code in codes %}
        {% if code.parent.pk == group.pk %}
            {% if code.pk == select %}
                <option selected value="{{ code.pk }}">{{ code }}</option>
            {% else %}
                <option value="{{ code.pk }}">{{ code }}</option>
            {% endif %}
        {% endif %}
    {% endfor %}
{% endfor %}

reportssite/non_repairability_act/templates/non_repairability_act/get_models.html
<option value="">---------</option>
{% for value in values %}
<option value="{{ value.pk }}">{{ value.title }}</option>
{% endfor %}

reportssite/non_repairability_act/templates/non_repairability_act/list.html
{% extends 'base.html' %}
{% load my_tags %}
{% load static %}

{% block title %}
    {{ block.super }}|Все акты НРП
{% endblock %}

{% block content %}
<div id="TopLevel"></div>
{% if request.user.is_staff %}
    {% include 'inc/staff_navbar.html' %}
{% else %}
    {% include 'inc/user_navbar.html' %}
{% endif %}


<div class="container col-lg-12">
    <div class="row py-4">
        <div class="col-12"><h3>Все акты:</h3></div>
    </div>

    <div class="row g-5">
        <div class="col-lg-4  order-lg-last">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-primary">Найдено актов</span>
                    <span class="badge bg-primary rounded-pill">{{ obj_count }}</span>
                </h4>
                <form class="card p-3 shadow pb-4" method="get">
                    <div class="row mb-1">
                        <label class="col-xl-4 col-form-label">Поиск</label>
                        <div class="col-8">
                            {{ form.filter }}
                        </div>
                    </div>
                    {% if request.user.is_staff %}
                    <div class="row mb-1  align-items-center">
                        <label class="col-xl-4 col-form-label">Сервис</label>
                        <div class="col-xl-8">
                            {{ form.service_center }}
                        </div>
                    </div>
                    {% endif %}
                    <div class="row mb-1  align-items-center">
                        <label class="col-xl-4">Статус</label>
                        <div class="col-xl-8">
                            {{ form.status }}
                        </div>
                    </div>
                    <div class="row mb-1 align-items-center">
                        <label class="col-xl-4 col-form-label">Отч. период</label>
                        <div class="col-xl-5">
                            {{ form.month }}
                        </div>
                        <div class="col-xl-3  align-items-center">
                            {{ form.year }}
                        </div>
                    </div>
                    <div class="container d-flex justify-content-center gap-2 mt-3">
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="bi bi-search"></i>
                            выбрать
                        </button>
                        <a class="btn btn-outline-primary" href="{% url 'act-list' %}" role="button">
                            <i class="bi bi-x-lg"></i>
                            сбросить
                        </a>
                    </div>
                </form>    
        </div>

        <div class="col-lg-8">
            {% for act in acts %}
            <div class="col mt-2 border border-dark shadow rounded pb-3" id="{{ act.pk }}">
                <div class="card-body ">
                    <!-- строка заголовка --> 
                    <div class="row py-1">
                        <h5 class="col">
                            {{ act.center.title }} ({{ act.center.city }}) № {{ act.pk }} от {{ act.doc_date|date:"d M Y"|lower}}
                        </h5> 
                        <div class="col-auto">
                            {% if request.user.is_staff %}
                                <a href="{% url 'act-staff-detail' act.pk %}" class="btn btn-outline-primary btn-sm">
                                    <i class="bi bi-eye"></i></i>
                                </a> 
                            {% else %}
                                <a href="{% url 'act-user-update' act.pk %}" class="btn btn-outline-primary btn-sm">
                                    <i class="bi bi-eye"></i></i>
                                </a>   
                            {% endif %}                            
                        </div>
                    </div>  
                    <!--Статус-->
                    <div class="row py-2">
                        <div class="col-фгещ">
                            {{ act.status|colored_act_status|safe }}
                        </div>
                    </div>
                    <!--Продавец и клиент -->
                    {% if act.shop or act.client %}
                    <div class="row">
                        {% if act.shop %}
                        <strong class="col-sm-2 text-muted">Продавец:</strong>
                        <div class="col-sm-4">{{ act.shop }}</div>
                        {% endif %}
                        {% if act.client %}
                        <strong class="col-sm-2 text-muted">Клиент:</strong>
                        <div class="col-sm-4">{{ act.client }}</div>
                        {% endif %}
                    </div>
                    {% endif %}
                    <!--Данные об изделии-->
                    {% if act.product or act.model_description or act.serial_number %}
                    <div class="row pb-2">                     
                        <div class="col-sm-6">{{ act.product|default_if_none:"" }}</div>
                        <div class="col-sm-3">{{ act.model_description|default_if_none:"" }}</div>
                        <div class="col-sm-3">{{ act.serial_number|default_if_none:"" }}</div>
                    </div>
                    {% endif %}
                    <!--Примечание-->
                    {% if act.note %}
                    <div class="col-12">
                        <i class="bi bi-info-square"></i><label class="px-3">{{ act.note }}</label>
                    </div>
                    {% endif %}
                    <!--Сообщение от менеджера -->
                    {% if act.member_for_user %}
                        {% if act.status.status == 'refinement' or request.user.is_staff %}
                        <div class="col-12">
                            <i class="bi bi-exclamation-square-fill text-danger"></i><strong class="px-3">{{ act.member_for_user }}</strong>
                        </div>
                        {% endif %}
                    {% endif %}
                </div>              
            </div>

            {% empty %}
                <h4 class="text-center text-muted">Ничего не найдено ...</h4>
            {% endfor %}
        </div>
    </div>
    {% if acts %}
        <!-- кнопка ВВЕРХ! -->
        {% include 'inc/go_to_top_button.html' %}
    {% endif %}
    {% include 'inc/list_paginator.html' %}

</div>


{% include 'inc/footer.html' %}


{% endblock %}